[project]
name = "robot-rent-project"
version = "0.1.0"
description = "This project is about predicting rent"
authors = [
    {name = "santhosh17august2003-cloud",email = "santhosh17august2003@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "Flask==3.1.2",
    "flask-cors==6.0.2",
    "pymongo==4.15.5",
    "dnspython==2.8.0",
    "numpy==2.3.5",
    "scikit-learn==1.8.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
